version: "3.8"

services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    networks:
      - integration
    depends_on:
      - db
    environment:
      - POSTGRES_DB=integration_db
      - DATA_STEAM_PATH=/app/data/SteamModified.csv
      - DATA_TWITCH_PATH=/app/data/Twitch_game_data.csv
      # set to true to initialize data from csv files
      # if database already has data prevent adding redundant data by setting to false
      - LOAD_DATA=false
  db:
    image: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - integration
    environment:
      - POSTGRES_DB=integration_db
      - POSTGRES_USER=integration
      - POSTGRES_PASSWORD=integration
    expose:
      - 5432
volumes:
  data:
# add secrets for password
networks:
  integration: